// Generated by scripts/generate_bridge_operations.py from api/napoleon_bridge.openapi.yaml.
// Do not edit by hand.

export const GENERATED_BRIDGE_CONTRACT_SOURCE = "api/napoleon_bridge.openapi.yaml" as const;

export const GENERATED_BRIDGE_OPERATIONS = [
  {
    id: "chief_of_staff_descriptor",
    path: "/v1/concierge/chief-of-staff/descriptor",
    requestKind: "chief_of_staff_descriptor",
    transport: "http_get",
    responseRequired: ["serviceId", "ready", "runtimeAuthority", "cachePolicy", "blockedEffects"],
    governedBridgeOnly: true,
    tokenPlacement: "authorization_header_only",
  },
  {
    id: "chief_of_staff_steering",
    path: "/v1/concierge/chief-of-staff/steering",
    requestKind: "chief_of_staff_steering_handoff",
    transport: "http_post",
    responseRequired: ["text", "governanceDecision", "traceEnvelope", "auditEnvelope", "appliedLocally", "memoryWritePerformed", "approvalCaptured", "agentDispatchPerformed", "externalSendPerformed"],
    governedBridgeOnly: true,
    tokenPlacement: "authorization_header_only",
  },
  {
    id: "evaluate",
    path: "/v1/concierge/evaluate",
    requestKind: "evaluator_prompt",
    transport: "http_post",
    responseRequired: ["text"],
    governedBridgeOnly: true,
    tokenPlacement: "authorization_header_only",
  },
  {
    id: "memory_proposal_review",
    path: "/v1/concierge/memory-proposals",
    requestKind: "memory_proposal_review_handoff",
    transport: "http_post",
    responseRequired: ["text", "governanceDecision", "traceEnvelope", "auditEnvelope", "memoryWritePerformed", "approvalCaptured", "agentDispatchPerformed", "externalSendPerformed"],
    governedBridgeOnly: true,
    tokenPlacement: "authorization_header_only",
  },
  {
    id: "text_turn",
    path: "/v1/concierge/turn",
    requestKind: "text_turn",
    transport: "http_post",
    responseRequired: ["text", "governanceDecision", "traceEnvelope", "auditEnvelope"],
    governedBridgeOnly: true,
    tokenPlacement: "authorization_header_only",
  },
] as const;
