#!/usr/bin/env python3
"""Generate the Concierge bridge operation registry from the OpenAPI contract."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "api/napoleon_bridge.openapi.yaml"
OUTPUT_PATH = ROOT / "app/src/generatedBridgeOperations.ts"

OPERATION_IDS_BY_PATH = {
    "/v1/concierge/turn": "text_turn",
    "/v1/concierge/chief-of-staff/descriptor": "chief_of_staff_descriptor",
    "/v1/concierge/chief-of-staff/steering": "chief_of_staff_steering",
    "/v1/concierge/memory-proposals": "memory_proposal_review",
    "/v1/concierge/evaluate": "evaluate",
}

DESCRIPTOR_REQUEST_KIND = "chief_of_staff_descriptor"

HTTP_METHOD_TO_TRANSPORT = {
    "get": "http_get",
    "post": "http_post",
}


def operation_method_for(path_spec: dict[str, Any], path: str) -> tuple[str, dict[str, Any]]:
    methods = [method for method in HTTP_METHOD_TO_TRANSPORT if method in path_spec]
    if len(methods) != 1:
        raise SystemExit(f"OpenAPI path must define exactly one supported bridge method: {path}")
    method = methods[0]
    return method, path_spec[method]


def request_kind_for(path: str, operation: dict[str, Any]) -> str:
    schema = (
        operation.get("requestBody", {})
        .get("content", {})
        .get("application/json", {})
        .get("schema", {})
    )
    request_kind = schema.get("properties", {}).get("requestKind", {}).get("const")
    if request_kind:
        return str(request_kind)
    if path == "/v1/concierge/chief-of-staff/descriptor":
        return DESCRIPTOR_REQUEST_KIND
    raise SystemExit(f"OpenAPI path lacks requestKind const: {path}")


def response_required_for(path: str, operation: dict[str, Any]) -> list[str]:
    schema = (
        operation.get("responses", {})
        .get("200", {})
        .get("content", {})
        .get("application/json", {})
        .get("schema", {})
    )
    required = schema.get("required")
    if not isinstance(required, list) or not all(isinstance(item, str) for item in required):
        raise SystemExit(f"OpenAPI path lacks 200 response required fields: {path}")
    return required


def generated_text() -> str:
    openapi = yaml.safe_load(SOURCE_PATH.read_text(encoding="utf-8"))
    paths = openapi.get("paths", {})
    operations = []
    for path, path_spec in sorted(paths.items()):
        if not path.startswith("/v1/concierge/"):
            continue
        operation_id = OPERATION_IDS_BY_PATH.get(path)
        if not operation_id:
            raise SystemExit(f"OpenAPI path lacks local bridge operation id mapping: {path}")
        method, operation = operation_method_for(path_spec, path)
        security = operation.get("security", [])
        if not any("NapoleonBearer" in entry for entry in security if isinstance(entry, dict)):
            raise SystemExit(f"OpenAPI path lacks NapoleonBearer security: {path}")
        operations.append(
            {
                "id": operation_id,
                "path": path,
                "requestKind": request_kind_for(path, operation),
                "transport": HTTP_METHOD_TO_TRANSPORT[method],
                "responseRequired": response_required_for(path, operation),
            }
        )

    lines = [
        "// Generated by scripts/generate_bridge_operations.py from api/napoleon_bridge.openapi.yaml.",
        "// Do not edit by hand.",
        "",
        'export const GENERATED_BRIDGE_CONTRACT_SOURCE = "api/napoleon_bridge.openapi.yaml" as const;',
        "",
        "export const GENERATED_BRIDGE_OPERATIONS = [",
    ]
    for operation in operations:
        lines.extend(
            [
                "  {",
                f'    id: "{operation["id"]}",',
                f'    path: "{operation["path"]}",',
                f'    requestKind: "{operation["requestKind"]}",',
                f'    transport: "{operation["transport"]}",',
                "    responseRequired: ["
                + ", ".join(f'"{field}"' for field in operation["responseRequired"])
                + "],",
                "    governedBridgeOnly: true,",
                '    tokenPlacement: "authorization_header_only",',
                "  },",
            ]
        )
    lines.extend(["] as const;", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args()

    expected = generated_text()
    if args.check:
        actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if actual != expected:
            raise SystemExit("app/src/generatedBridgeOperations.ts is stale; run scripts/generate_bridge_operations.py")
        print("generated bridge operations are current")
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
