#!/usr/bin/env python3
"""Audit Concierge's current evidence against the Napoleon UI goal."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ALIGNMENT_REPORT_PATH = Path("/tmp/concierge-napoleon-alignment.json")
EXPECTED_RUNTIME_HANDOFF_KIND = "concierge.runtime-handoff-status.v1"


@dataclass(frozen=True)
class EvidenceCheck:
    path: str
    contains: tuple[str, ...] = ()
    description: str = ""


@dataclass(frozen=True)
class Requirement:
    id: str
    requirement: str
    evidence: tuple[EvidenceCheck, ...]
    external_blocker_marker: str | None = None
    blocker_owner: str | None = None
    next_action: str | None = None
    napoleon_required_action: dict[str, Any] | None = None
    validation: tuple[str, ...] = ()


@dataclass(frozen=True)
class AcceptanceCriterion:
    id: str
    criterion: str
    requirement_ids: tuple[str, ...]


REQUIREMENTS: tuple[Requirement, ...] = (
    Requirement(
        id="descriptor_first_class_connection_state",
        requirement="Treat Napoleon descriptor discovery as first-class connection state.",
        validation=("make check",),
        evidence=(
            EvidenceCheck("app/src/descriptorDiscovery.ts", ("descriptor", "checksum", "signature")),
            EvidenceCheck("app/tests/descriptorDiscovery.test.ts", ("descriptor", "fail", "runtimeAuthority")),
            EvidenceCheck("docs/BACKLOG.md", ("descriptor", "connection state")),
        ),
    ),
    Requirement(
        id="generated_bridge_client_alignment",
        requirement="Keep the governed bridge operation registry aligned to the canonical OpenAPI contract.",
        validation=("make bridge-operations-check", "make check"),
        evidence=(
            EvidenceCheck("scripts/generate_bridge_operations.py", ("api/napoleon_bridge.openapi.yaml",)),
            EvidenceCheck("app/src/generatedBridgeOperations.ts", ("Generated by scripts/generate_bridge_operations.py",)),
            EvidenceCheck("app/tests/bridgeOperations.test.ts", ("GENERATED_BRIDGE_CONTRACT_SOURCE",)),
            EvidenceCheck("Makefile", ("bridge-operations-check",)),
        ),
    ),
    Requirement(
        id="napoleon_delegation_panel",
        requirement="Show Napoleon delegation state, selected agents, effects, governance, trace, and audit proof.",
        validation=("cd app && npm test", "make check"),
        evidence=(
            EvidenceCheck("app/src/App.tsx", ("aria-label=\"Napoleon delegation\"", "selectedAgents")),
            EvidenceCheck("app/tests/AppProofExportInteraction.test.tsx", ("Napoleon delegation", "Selected agents")),
            EvidenceCheck("app/tests/AppSelectedAgentProofInteraction.test.tsx", ("selected", "agent")),
            EvidenceCheck("evaluator/scenarios.yaml", ("DELEGATION-PANEL-STATE-001",)),
        ),
    ),
    Requirement(
        id="response_authority_provenance",
        requirement="Render Napoleon and selected-agent contributions only from returned bridge proof.",
        validation=("cd app && npm test", "make check"),
        evidence=(
            EvidenceCheck("app/src/napoleonResponsePresentation.ts", ("recommendation", "contribution")),
            EvidenceCheck("app/src/napoleonBridge.ts", ("selectedAgents", "provenance")),
            EvidenceCheck("app/tests/napoleonResponsePresentation.test.ts", ("Napoleon recommends", "Passive Brain")),
            EvidenceCheck("evaluator/scenarios.yaml", ("BRIDGE-RESPONSE-PROVENANCE-001",)),
        ),
    ),
    Requirement(
        id="fail_closed_bridge_states",
        requirement="Fail closed for missing descriptor, auth, contract mismatch, no_go, deny, and timeout states.",
        validation=("cd app && npm test", "make eval", "make check"),
        evidence=(
            EvidenceCheck("app/src/napoleonBridge.ts", ("missing_descriptor", "contract_mismatch", "timeout")),
            EvidenceCheck("app/tests/AppProofExportInteraction.test.tsx", ("governance_no_go", "bridge_timeout")),
            EvidenceCheck("app/tests/napoleonBridge.test.ts", ("auth", "contract_mismatch", "governance_no_go")),
            EvidenceCheck("evaluator/scenarios.yaml", ("BRIDGE-FAILURE-001", "CONTRACT-MISMATCH-001")),
        ),
    ),
    Requirement(
        id="chief_of_staff_steering_proposal_only",
        requirement="Aggregate capability signals into proposal-only Chief of Staff steering drafts and governed handoffs.",
        validation=("cd app && npm test", "make eval", "make check"),
        evidence=(
            EvidenceCheck("app/src/chiefOfStaffSteering.ts", ("proposal", "recommendationType")),
            EvidenceCheck("app/src/capabilityLedger.ts", ("architectureArea", "recommended")),
            EvidenceCheck("app/tests/chiefOfStaffSteering.test.ts", ("proposal", "memoryWriteAllowed")),
            EvidenceCheck("evaluator/scenarios.yaml", ("CAPABILITY-INTELLIGENCE-STEERING-TYPES-001",)),
        ),
    ),
    Requirement(
        id="authority_boundary_validation",
        requirement="Reject direct agent calls, tool calls, memory writes, approval capture, and external sends in Concierge code.",
        validation=("make schema-check", "make check"),
        evidence=(
            EvidenceCheck("scripts/validate_repo.py", ("direct agent or tool dispatch", "direct memory or graph access")),
            EvidenceCheck("evaluator/tests/test_authority_boundary_validation.py", ("invokeAgent", "direct memory or graph access")),
            EvidenceCheck("docs/GOVERNANCE_SAFETY_PRIVACY.md", ("Concierge", "Napoleon")),
        ),
    ),
    Requirement(
        id="rehearsal_mode_local_only",
        requirement="Keep Rehearsal Mode local and prevent live Napoleon contact while previewing governed turns.",
        validation=("cd app && npm test", "make eval", "make check"),
        evidence=(
            EvidenceCheck("docs/REHEARSAL_MODE.md", ("local", "Napoleon")),
            EvidenceCheck("app/src/App.tsx", ("rehearsal", "preview")),
            EvidenceCheck("app/tests/AppProofExportInteraction.test.tsx", ("Rehearsal", "Napoleon")),
            EvidenceCheck("evaluator/scenarios.yaml", ("REHEARSAL-ADULT-001", "REHEARSAL-ADVERSARIAL-001")),
        ),
    ),
    Requirement(
        id="capability_intelligence_local_only",
        requirement="Answer common, working, missing, and recommended capability questions from bounded local metadata.",
        validation=("cd app && npm test", "make eval", "make check"),
        evidence=(
            EvidenceCheck("docs/CONVERSATION_CAPABILITY_INTELLIGENCE.md", ("common", "missing", "recommended")),
            EvidenceCheck("app/src/capabilityLedger.ts", ("profileScope", "sanitized")),
            EvidenceCheck("app/tests/capabilityLedger.test.ts", ("raw", "profile")),
            EvidenceCheck("evaluator/scenarios.yaml", ("CAPABILITY-INTELLIGENCE-001",)),
        ),
    ),
    Requirement(
        id="child_protected_stricter_boundary",
        requirement="Keep child protected mode stricter than adult owner mode.",
        validation=("cd app && npm test", "make eval", "make check"),
        evidence=(
            EvidenceCheck("docs/GOVERNANCE_SAFETY_PRIVACY.md", ("Child", "guardian")),
            EvidenceCheck("app/tests/avatarChildConstraints.test.ts", ("child", "guardian")),
            EvidenceCheck("evaluator/scenarios.yaml", ("CHILD-BRIDGE-RESPONSE-SEMANTICS-001",)),
        ),
    ),
    Requirement(
        id="evolution_status_runtime_blocker",
        requirement="Refresh evolution proposal status only through a descriptor-advertised read-only Napoleon route.",
        blocker_owner="napoleon_runtime",
        next_action=(
            "Expose and advertise the read-only evolution_proposal_status runtime target at "
            "/evolution/proposals/{proposal_id}/status with request kind evolution_proposal_status_handoff."
        ),
        validation=(
            "NAPOLEON_CONTRACT_OPENAPI=/path/to/concierge-integration.openapi.yaml make napoleon-contract-alignment",
            "make goal-completion-audit",
            "NAPOLEON_EVAL_ENDPOINT=<local-url> make eval-http",
            "make check",
        ),
        evidence=(
            EvidenceCheck("app/src/evolutionProposalStatus.ts", ("evolution_proposal_status", "appliedLocally")),
            EvidenceCheck("app/tests/evolutionProposalSubmission.test.ts", ("evolution proposal status refresh",)),
            EvidenceCheck("docs/NAPOLEON_CONTRACT_ALIGNMENT.md", ("evolution_proposal_status", "blockingLivePromotion")),
            EvidenceCheck("app/src/bridgeOperations.ts", ("blockingLivePromotion: true", "expose_evolution_proposal_status_runtime_target")),
        ),
        external_blocker_marker="expose_evolution_proposal_status_runtime_target",
        napoleon_required_action={
            "id": "expose_evolution_proposal_status_runtime_target",
            "owner": "napoleon_runtime",
            "operationId": "evolution_proposal_status",
            "targetPath": "/evolution/proposals/{proposal_id}/status",
            "requestKind": "evolution_proposal_status_handoff",
            "advertiseUsing": ["supportedHandoffs", "required_for"],
            "blockingLivePromotion": True,
            "boundary": (
                "Napoleon-owned runtime exposure only; Concierge must not infer approval, call free-form paths, "
                "apply evolution, write memory, dispatch agents, send externally, or treat status as local authority."
            ),
            "approvalCaptured": False,
            "memoryWritePerformed": False,
            "agentDispatchPerformed": False,
            "externalSendPerformed": False,
            "appliedLocally": False,
        },
    ),
)


ACCEPTANCE_CRITERIA: tuple[AcceptanceCriterion, ...] = (
    AcceptanceCriterion(
        id="send_text_request_to_napoleon",
        criterion="User can send one text request through Concierge to Napoleon.",
        requirement_ids=("descriptor_first_class_connection_state", "generated_bridge_client_alignment"),
    ),
    AcceptanceCriterion(
        id="show_handling_capability_or_agent",
        criterion="Concierge shows which Napoleon capability or agent handled the request.",
        requirement_ids=("napoleon_delegation_panel", "response_authority_provenance"),
    ),
    AcceptanceCriterion(
        id="speak_from_returned_bridge_contributions",
        criterion=(
            "Concierge can say Napoleon recommends something or a selected agent found something only when "
            "the bridge response contains that contribution."
        ),
        requirement_ids=("response_authority_provenance",),
    ),
    AcceptanceCriterion(
        id="blocked_effects_visible",
        criterion="All blocked effects are visible.",
        requirement_ids=("napoleon_delegation_panel", "fail_closed_bridge_states"),
    ),
    AcceptanceCriterion(
        id="no_go_stops_forwarding",
        criterion="No-go decisions stop forwarding.",
        requirement_ids=("fail_closed_bridge_states", "authority_boundary_validation"),
    ),
    AcceptanceCriterion(
        id="rehearsal_preview_local_only",
        criterion="Rehearsal preview never calls live Napoleon.",
        requirement_ids=("rehearsal_mode_local_only",),
    ),
    AcceptanceCriterion(
        id="capability_intelligence_drafts_only",
        criterion="Capability Intelligence can draft, but not apply, evolution proposals.",
        requirement_ids=("capability_intelligence_local_only", "chief_of_staff_steering_proposal_only"),
    ),
    AcceptanceCriterion(
        id="evolution_status_runtime_status_route",
        criterion="Read-only evolution proposal status refresh has a descriptor-advertised Napoleon route.",
        requirement_ids=("evolution_status_runtime_blocker",),
    ),
)


def _read(path: str) -> str | None:
    file_path = ROOT / path
    if not file_path.exists():
        return None
    return file_path.read_text(encoding="utf-8", errors="replace")


def evaluate_check(check: EvidenceCheck) -> dict[str, Any]:
    content = _read(check.path)
    if content is None:
        return {
            "path": check.path,
            "status": "missing",
            "description": check.description,
            "matchedTerms": [],
            "missingTerms": list(check.contains),
        }
    matched = [term for term in check.contains if term in content]
    missing = [term for term in check.contains if term not in content]
    return {
        "path": check.path,
        "status": "present" if not missing else "partial",
        "description": check.description,
        "matchedTerms": matched,
        "missingTerms": missing,
    }


def _resolve_alignment_report_path(
    explicit_path: Path | None,
    default_path: Path | None = DEFAULT_ALIGNMENT_REPORT_PATH,
) -> Path | None:
    if explicit_path is not None:
        return explicit_path
    if default_path is not None and default_path.exists():
        return default_path
    return None


def _load_alignment_report(path: Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _load_runtime_handoff_report(path: Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _alignment_report_clears_blocker(report: dict[str, Any] | None, marker: str | None) -> bool:
    if report is None or marker != "expose_evolution_proposal_status_runtime_target":
        return False
    if report.get("kind") != "concierge.napoleon-contract-alignment.v1":
        return False
    if report.get("nonAuthorityBoundary") != "alignment_check_only":
        return False
    for flag in (
        "sideEffectsPerformed",
        "approvalCaptured",
        "memoryWritePerformed",
        "agentDispatchPerformed",
        "externalSendPerformed",
    ):
        if report.get(flag) is not False:
            return False
    if report.get("runtimeAligned") is not True or report.get("blockingLivePromotion") is not False:
        return False
    supported_paths = report.get("supportedReviewRuntimePaths")
    if not isinstance(supported_paths, list) or "/evolution/proposals/{proposal_id}/status" not in supported_paths:
        return False
    required_actions = report.get("napoleonRequiredActions")
    if not isinstance(required_actions, list):
        return False
    return not any(isinstance(action, dict) and action.get("id") == marker for action in required_actions)


def _safe_alignment_evidence_summary(report: dict[str, Any] | None, path: Path | None) -> dict[str, Any]:
    missing_targets: list[str] = []
    required_action_count: int | None = None
    alignment_status: str | None = None
    runtime_aligned: bool | None = None
    blocking_live_promotion: bool | None = None
    if report is not None:
        raw_missing_targets = report.get("conciergeReviewPathsMissingFromNapoleonRuntime")
        if isinstance(raw_missing_targets, list):
            missing_targets = [item for item in raw_missing_targets if isinstance(item, str)]
        if isinstance(report.get("napoleonRequiredActionCount"), int):
            required_action_count = report["napoleonRequiredActionCount"]
        if isinstance(report.get("alignmentStatus"), str):
            alignment_status = report["alignmentStatus"]
        if isinstance(report.get("runtimeAligned"), bool):
            runtime_aligned = report["runtimeAligned"]
        if isinstance(report.get("blockingLivePromotion"), bool):
            blocking_live_promotion = report["blockingLivePromotion"]

    return {
        "path": str(path) if path else None,
        "loaded": report is not None,
        "canClearEvolutionStatusBlocker": _alignment_report_clears_blocker(
            report,
            "expose_evolution_proposal_status_runtime_target",
        ),
        "alignmentStatus": alignment_status,
        "runtimeAligned": runtime_aligned,
        "blockingLivePromotion": blocking_live_promotion,
        "napoleonRequiredActionCount": required_action_count,
        "missingRuntimeTargets": missing_targets,
        "nonAuthorityBoundary": "alignment_report_only",
    }


def _runtime_handoff_report_is_safe(report: dict[str, Any] | None) -> bool:
    if report is None or report.get("kind") != EXPECTED_RUNTIME_HANDOFF_KIND:
        return False
    boundary = report.get("boundary")
    if not isinstance(boundary, dict):
        return False
    required_true = (
        "localHandoffEvidenceOnly",
        "doesNotContactNapoleon",
        "doesNotApprove",
        "doesNotWriteMemory",
        "doesNotDispatchAgents",
        "doesNotSendExternally",
        "doesNotApplyEvolution",
    )
    required_false = (
        "endpointHostRetained",
        "tokenRetained",
        "tokenFilePathRetained",
        "requestBodyRetained",
        "responseBodyRetained",
    )
    return all(boundary.get(key) is True for key in required_true) and all(
        boundary.get(key) is False for key in required_false
    )


def _safe_runtime_handoff_evidence_summary(report: dict[str, Any] | None, path: Path | None) -> dict[str, Any]:
    if not _runtime_handoff_report_is_safe(report):
        return {
            "path": str(path) if path else None,
            "loaded": False,
            "canProceed": None,
            "nextAction": None,
            "localBlockerCount": 0,
            "externalBlockerCount": 0,
            "blockerIds": [],
            "authProvisioning": {
                "tokenConfigured": None,
                "tokenFileConfigured": None,
                "tokenFileReadable": None,
                "tokenRetained": False,
                "tokenFilePathRetained": False,
            },
            "nonAuthorityBoundary": "runtime_handoff_report_only",
        }
    readiness = report.get("readiness") if isinstance(report.get("readiness"), dict) else {}
    auth = report.get("authProvisioning") if isinstance(report.get("authProvisioning"), dict) else {}
    blockers = readiness.get("blockers") if isinstance(readiness.get("blockers"), list) else []
    sanitized_blockers = [blocker for blocker in blockers if isinstance(blocker, dict)]
    return {
        "path": str(path) if path else None,
        "loaded": True,
        "canProceed": readiness.get("canProceed") if isinstance(readiness.get("canProceed"), bool) else None,
        "nextAction": readiness.get("nextAction") if isinstance(readiness.get("nextAction"), str) else None,
        "localBlockerCount": sum(1 for blocker in sanitized_blockers if blocker.get("external") is False),
        "externalBlockerCount": sum(1 for blocker in sanitized_blockers if blocker.get("external") is True),
        "blockerIds": [blocker["id"] for blocker in sanitized_blockers if isinstance(blocker.get("id"), str)],
        "authProvisioning": {
            "tokenConfigured": auth.get("tokenConfigured") if isinstance(auth.get("tokenConfigured"), bool) else None,
            "tokenFileConfigured": (
                auth.get("tokenFileConfigured") if isinstance(auth.get("tokenFileConfigured"), bool) else None
            ),
            "tokenFileReadable": (
                auth.get("tokenFileReadable") if isinstance(auth.get("tokenFileReadable"), bool) else None
            ),
            "tokenRetained": False,
            "tokenFilePathRetained": False,
        },
        "nonAuthorityBoundary": "runtime_handoff_report_only",
    }


def _runtime_handoff_requirements(report: dict[str, Any] | None) -> list[dict[str, Any]]:
    if not _runtime_handoff_report_is_safe(report):
        return []
    readiness = report.get("readiness") if isinstance(report.get("readiness"), dict) else {}
    blockers = readiness.get("blockers") if isinstance(readiness.get("blockers"), list) else []
    requirements: list[dict[str, Any]] = []
    for blocker in blockers:
        if not isinstance(blocker, dict) or blocker.get("id") != "token_file_unreadable":
            continue
        requirements.append(
            {
                "id": "runtime_handoff_token_access",
                "requirement": "Concierge runtime handoff has approved readable token-file access.",
                "status": "local_blocker",
                "evidence": [
                    {
                        "path": "scripts/runtime_handoff_status.py",
                        "status": "present",
                        "description": "Sanitized retained runtime handoff report supplied to audit.",
                        "matchedTerms": ["tokenFileConfigured", "tokenFileReadable"],
                        "missingTerms": [],
                    }
                ],
                "validation": ["make runtime-handoff-status", "make goal-completion-audit", "make check"],
                "blocker": {
                    "owner": "concierge_operator",
                    "nextAction": blocker.get("nextAction")
                    if isinstance(blocker.get("nextAction"), str)
                    else "Provision approved runtime token-file access without copying token values into artifacts.",
                    "external": False,
                },
            }
        )
    return requirements


def evaluate_requirement(requirement: Requirement, alignment_report: dict[str, Any] | None = None) -> dict[str, Any]:
    checks = [evaluate_check(check) for check in requirement.evidence]
    present_count = sum(1 for check in checks if check["status"] == "present")
    missing_count = sum(1 for check in checks if check["status"] == "missing")
    partial_count = sum(1 for check in checks if check["status"] == "partial")
    status = "proven"
    if requirement.external_blocker_marker and _read("app/src/bridgeOperations.ts"):
        bridge_ops = _read("app/src/bridgeOperations.ts") or ""
        if requirement.external_blocker_marker in bridge_ops and "blockingLivePromotion: true" in bridge_ops:
            status = "external_blocker"
        if status == "external_blocker" and _alignment_report_clears_blocker(
            alignment_report,
            requirement.external_blocker_marker,
        ):
            status = "proven"
    if status == "proven" and (missing_count or partial_count):
        status = "weak_evidence" if present_count else "missing_evidence"
    result: dict[str, Any] = {
        "id": requirement.id,
        "requirement": requirement.requirement,
        "status": status,
        "evidence": checks,
        "validation": list(requirement.validation),
    }
    if status in {"external_blocker", "missing_evidence", "weak_evidence"}:
        blocker = {
            "owner": requirement.blocker_owner or "concierge",
            "nextAction": requirement.next_action
            or "Add or repair the listed evidence, then rerun the requirement validation commands.",
            "external": status == "external_blocker",
        }
        if requirement.napoleon_required_action is not None:
            blocker["napoleonRequiredAction"] = dict(requirement.napoleon_required_action)
        result["blocker"] = blocker
    return result


def evaluate_acceptance_criteria(requirements: list[dict[str, Any]]) -> list[dict[str, Any]]:
    requirements_by_id = {requirement["id"]: requirement for requirement in requirements}
    criteria: list[dict[str, Any]] = []
    for criterion in ACCEPTANCE_CRITERIA:
        requirement_ids = list(criterion.requirement_ids)
        if criterion.id == "send_text_request_to_napoleon" and "runtime_handoff_token_access" in requirements_by_id:
            requirement_ids.append("runtime_handoff_token_access")
        linked_requirements = [
            requirements_by_id[requirement_id]
            for requirement_id in requirement_ids
            if requirement_id in requirements_by_id
        ]
        blocking_requirement_ids = [
            requirement["id"] for requirement in linked_requirements if requirement["status"] != "proven"
        ]
        statuses = {requirement["status"] for requirement in linked_requirements}
        status = "proven"
        if "external_blocker" in statuses:
            status = "external_blocker"
        elif "local_blocker" in statuses:
            status = "local_blocker"
        elif "missing_evidence" in statuses:
            status = "missing_evidence"
        elif "weak_evidence" in statuses:
            status = "weak_evidence"
        criteria.append(
            {
                "id": criterion.id,
                "criterion": criterion.criterion,
                "status": status,
                "requirementIds": requirement_ids,
                "blockingRequirementIds": blocking_requirement_ids,
            }
        )
    return criteria


def build_report(
    alignment_report_path: Path | None = None,
    default_alignment_report_path: Path | None = DEFAULT_ALIGNMENT_REPORT_PATH,
    runtime_handoff_status_path: Path | None = None,
) -> dict[str, Any]:
    resolved_alignment_report_path = _resolve_alignment_report_path(
        alignment_report_path,
        default_alignment_report_path,
    )
    alignment_report = _load_alignment_report(resolved_alignment_report_path)
    runtime_handoff_report = _load_runtime_handoff_report(runtime_handoff_status_path)
    requirements = [evaluate_requirement(requirement, alignment_report) for requirement in REQUIREMENTS]
    requirements.extend(_runtime_handoff_requirements(runtime_handoff_report))
    acceptance_criteria = evaluate_acceptance_criteria(requirements)
    acceptance_criteria_status_counts: dict[str, int] = {}
    for criterion in acceptance_criteria:
        acceptance_criteria_status_counts[criterion["status"]] = (
            acceptance_criteria_status_counts.get(criterion["status"], 0) + 1
        )
    status_counts: dict[str, int] = {}
    for requirement in requirements:
        status_counts[requirement["status"]] = status_counts.get(requirement["status"], 0) + 1
    blocker_statuses = {"external_blocker", "local_blocker", "missing_evidence", "weak_evidence"}
    blockers = [item for item in requirements if item["status"] in blocker_statuses]
    overall_status = "goal_not_complete" if blockers else "all_local_evidence_present"
    blocker_summaries = [
        {
            "requirementId": item["id"],
            "owner": item["blocker"]["owner"],
            "nextAction": item["blocker"]["nextAction"],
            "external": item["blocker"]["external"],
            "validation": item["validation"],
            **(
                {"napoleonRequiredAction": item["blocker"]["napoleonRequiredAction"]}
                if "napoleonRequiredAction" in item["blocker"]
                else {}
            ),
        }
        for item in blockers
    ]
    next_actions = [dict(blocker) for blocker in blocker_summaries]
    completion_gate = {
        "canCloseGoal": not blockers,
        "acceptanceCriteriaSatisfied": all(
            criterion["status"] == "proven" for criterion in acceptance_criteria
        ),
        "blockingRequirementIds": [item["id"] for item in blockers],
        "externalBlockerCount": sum(1 for item in blockers if item["blocker"]["external"]),
        "localBlockerCount": sum(1 for item in blockers if not item["blocker"]["external"]),
        "requiredBeforeClose": [
            "make check",
            "make eval",
            "make goal-completion-audit",
            "NAPOLEON_EVAL_ENDPOINT=<local-url> make eval-http when a real Napoleon endpoint is available",
        ],
        "validationCommandsExecutedByAudit": False,
        "validationEvidenceSource": "not_executed_by_goal_completion_audit",
        "reason": "All audited requirements must be proven and no external blocker may remain.",
    }
    completion_gate["requiredButNotRunByAudit"] = list(completion_gate["requiredBeforeClose"])
    return {
        "kind": "concierge.goal-completion-audit.v1",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "overallStatus": overall_status,
        "alignmentEvidence": _safe_alignment_evidence_summary(alignment_report, resolved_alignment_report_path),
        "runtimeHandoffEvidence": _safe_runtime_handoff_evidence_summary(
            runtime_handoff_report,
            runtime_handoff_status_path,
        ),
        "statusCounts": status_counts,
        "acceptanceCriteriaStatusCounts": acceptance_criteria_status_counts,
        "requirementCount": len(requirements),
        "acceptanceCriteriaCount": len(acceptance_criteria),
        "blockerCount": len(blockers),
        "blockers": blocker_summaries,
        "nextActions": next_actions,
        "completionGate": completion_gate,
        "acceptanceCriteria": acceptance_criteria,
        "requirements": requirements,
        "boundary": {
            "localEvidenceOnly": True,
            "doesNotContactNapoleon": True,
            "doesNotApprove": True,
            "doesNotWriteMemory": True,
            "doesNotDispatchAgents": True,
            "doesNotSendExternally": True,
            "doesNotApplyEvolution": True,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", help="Optional JSON output path.")
    parser.add_argument(
        "--contract-alignment-report",
        type=Path,
        help="Optional JSON report from make napoleon-contract-alignment used as fresh non-authorizing runtime evidence.",
    )
    parser.add_argument(
        "--runtime-handoff-status",
        type=Path,
        help="Optional sanitized JSON report from make runtime-handoff-status used as local provisioning evidence.",
    )
    parser.add_argument("--quiet", action="store_true", help="Print only JSON path/status summary.")
    args = parser.parse_args()

    report = build_report(
        alignment_report_path=args.contract_alignment_report,
        runtime_handoff_status_path=args.runtime_handoff_status,
    )
    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if args.quiet:
        if args.out:
            print(f"{report['overallStatus']} {args.out}")
        else:
            print(report["overallStatus"])
    else:
        print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
